version: "3.9"

volumes:
   pg-data:
   
services:
  feed:
    build: ./feed
    ports:
      - "4000:4000"
  db:
    image: postgres
    volumes:
      - pg-data:/pg-data
    environment:
      - POSTGRES_DB=tempfeed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pg-data
  consumer:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/tempFeedConsumer
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=tempfeed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - feed

