# Generated by Django 4.0.4 on 2022-05-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingDateTime', models.DateTimeField(verbose_name='reading datetime')),
                ('tempReading', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
