# Generated by Django 3.2.12 on 2022-06-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempFeedConsumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempreading',
            old_name='tempReading',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='tempreading',
            old_name='readingDateTime',
            new_name='timestamp',
        ),
    ]
