# Generated by Django 3.2.12 on 2022-06-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempFeedConsumer', '0002_auto_20220601_0623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempReading',
            new_name='Reading',
        ),
    ]
