# Generated by Django 3.2.12 on 2022-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempFeedConsumer', '0004_alter_reading_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
